# Generated by Django 4.2 on 2023-05-02 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tuyensinhapp', '0003_alter_admissioninfo_type_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='adInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='tuyensinhapp.admissioninfo'),
        ),
        migrations.CreateModel(
            name='Comment_replie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('content', models.CharField(max_length=255)),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuyensinhapp.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
