# Generated by Django 4.2 on 2023-05-03 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tuyensinhapp', '0005_notification_alter_comment_replie_comment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('question', models.CharField(max_length=255)),
                ('noti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuyensinhapp.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
