# Generated by Django 4.2 on 2023-05-04 10:55

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tuyensinhapp', '0008_alter_notification_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('introduce', models.CharField(max_length=500)),
                ('description', ckeditor.fields.RichTextField()),
                ('website', models.URLField(max_length=255)),
                ('intro_video', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major', to='tuyensinhapp.department')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('minimum_score', models.FloatField()),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='tuyensinhapp.major')),
            ],
        ),
    ]
