# Generated by Django 4.2 on 2023-05-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuyensinhapp', '0009_department_major_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to='banners/%Y/%m')),
            ],
        ),
        migrations.AddField(
            model_name='question_notification',
            name='answer',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
