# Generated by Django 4.2 on 2023-05-05 04:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuyensinhapp', '0010_banner_question_notification_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', ckeditor.fields.RichTextField()),
                ('hotline', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('mail', models.CharField(max_length=100)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
