# Generated by Django 4.2 on 2023-05-09 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuyensinhapp', '0012_banner_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_notification',
            name='user',
        ),
    ]
