# Generated by Django 4.2 on 2023-05-10 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tuyensinhapp', '0013_remove_question_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_notification',
            name='isAnswer',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AlterField(
            model_name='question_notification',
            name='noti',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='tuyensinhapp.notification'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ManyToManyField(limit_choices_to={'type__id__in': ['3']}, null=True, related_name='noti', to=settings.AUTH_USER_MODEL),
        ),
    ]
