# Generated by Django 4.2 on 2023-05-10 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tuyensinhapp', '0015_question_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_notification',
            name='update_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ManyToManyField(limit_choices_to={'type__id__in': ['3']}, related_name='noti', to=settings.AUTH_USER_MODEL),
        ),
    ]
